<?php
/**
 * $Id: shareomatic.module,v 1.5 2008/03/21 22:46:16 sdog Exp $
 *
 * @file
 * Author: Kris Buytaert - http://www.krisbuytaert.be/blog/
 * 
 * Author: Ramiro Gómez - http://www.ramiro.org
 * A Drupal module that adds a ShareoMatic this button to your nodes.
 * The code of this module is heavily based on the DiggIT  module by Ramiro Gómez - http://www.ramiro.org
 * The code of this module is partially based on the service links module by Fredrik Jonsson
 */
/**
 * Implementation of hook_menu().
 */
function shareomatic_menu($may_cache) {
  $items = array();
  $items[] = array(
    'path' => 'admin/settings/shareomatic',
    'title' => t('Shareomatic'),
    'description' => t('Enable the node types and set the properties for the shareomatic button.'),
    'callback' => 'drupal_get_form',
    'callback arguments' => array('shareomatic_admin_settings'),
    'access' => user_access('administer site configuration'),
    'type' => MENU_NORMAL_ITEM
  );
  return $items;
}

/**
 * admin settings for the shareomatic module
 */
function shareomatic_admin_settings() {
  $form = array();
  $form['shareomatic'] = array(
    '#type' => 'fieldset',
    '#title' => 'Shareomatic ' . t('settings')
  );
  
  $form['shareomatic']['shareomatic_button_skin'] = array(
    '#type' => 'select',
    '#title' => t('Button skin'),
    '#default_value' => variable_get('shareomatic_button_skin', 'standard'),
    '#options' => array(
      'standard' => t('standard'),
      'compact' => t('compact')
     ),
    '#description' => t('The Button skin option controls the look at the button. If set to <em>standard</em> the button defaults to a standard digg button (much like the one you see on Digg itself). If specified as <em>compact</em>, then a smaller horizontal visual design is used that will fit better into a list of links.')
  );
  
  $form['shareomatic']['shareomatic_button_bgcolor'] = array(
    '#type' => 'textfield',
    '#title' => t('Button background color'),
    '#default_value' => variable_get('shareomatic_button_bgcolor', ''),
    '#size' => 7,
    '#maxlength' => 7,
    '#description' => t('Enter a hexadecimal color value here, e.g. <code>#ff9900</code>. Include the leading <code>#</code> and enter 6 numbers/digits')
  );
  
  $form['shareomatic']['shareomatic_button_weight'] = array(
    '#type' => 'select',
    '#title' => t('Weight'),
    '#default_value' => variable_get('shareomatic_button_weight', 10),
    '#options' => drupal_map_assoc(range(-20,20)),
    '#description' => t('Specifies the position of the shareomatic button. A low weight, e.g. <strong>-20</strong> will display the button above the content and a high weight, e.g. <strong>20</strong> below the content.')
  );

  $form['shareomatic']['shareomatic_node_types'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Node Types'),
    '#default_value' => variable_get('shareomatic_node_types', array()),
    '#options' => node_get_types('names'),
    '#description' => t('activate the node types in where the digg button shall be displayed')
  );
  return system_settings_form($form);
}
/**
 * Implementation of hook_nodeapi().
 */
function shareomatic_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  // we're in full node view
  if ($op == 'view' && !$a3) {
    //Check our node is one of the ok types
    if(in_array($node->type, variable_get('shareomatic_node_types', array()), TRUE)) {
      $node->content['shareomatic_button'] = array(
        '#value' => theme('shareomatic_button', $node),
        '#weight' => variable_get('shareomatic_button_weight', 10)
      );
    }
  }
}

/**
 * theme function for button display
 */
function theme_shareomatic_button($node) {
  // add shareomatic css file
  $module_path = drupal_get_path('module','shareomatic');
  drupal_add_css($module_path . '/shareomatic.css');
  
  // absolute url of the current node
  $url = url('node/'. $node->nid, NULL, NULL, TRUE);
  
  // only set the background color if set
  $bgcolor = variable_get('shareomatic_button_bgcolor', '');
  if ($bgcolor) {
    $bg_string = "digg_bgcolor = '$bgcolor';";
  }
  
  $skin = variable_get('shareomatic_button_skin', 'standard');
  $title = drupal_to_js($node->title);
  


 $linkimage = 'http://www.shareomatic.com/images/s_16_black.gif'; 
 $linktext = 'Share with Shareomatic!';
 $shareomaticbutton = '<div class="sharomaticbutton"> <a href="http://www.shareomatic.com/'.$url.'/shareomatic-drupal/'.' '.$node->title.'"><img src="'.$linkimage.'" alt="Share with Shareomatic!" 
			title="Post this item on various social news sites with Shareomatic!"/></a> <a href="http://www.shareomatic.com/'.$url.'/shareomatic-drupal/'.' '.$node->title.'">'.$linktext.'</a> </div>';  
 
 return $shareomaticbutton;
 

}
?>
